#! /bin/sh

# For local tests, we just run the process.  We could bind to remote
# CPUs if we wanted.

# Redirect everything so this doesn't hold socket open.
./virtclient dummy$1 $2 >/dev/tty < /dev/null 2>&1 &
jobs -p %1
