#! /bin/sh

. ./SETTINGS

# For local tests, we just run the process.  We could bind to remote
# CPUs if we wanted.

# Redirect everything so this doesn't hold socket open.
./virtclient $1 $2 $3 scratchfile >/dev/tty < /dev/null 2>&1 &
jobs -p %1
