#! /bin/sh

. lguest/SETTINGS

# Redirect everything so this doesn't hold socket open.
$LGUEST 512m $1 $KERNEL --block=rootfs/virtbench-root-$1 --tunnet=192.168.12.$(($1+1)) --sharenet=$SHARENET_FILE root=/dev/lgba rw debug init=/virtclient $1 `echo $2 | tr . /` $3 eth0 192/168/19/$(($1+1)) eth1 > $LOGFILES-$1 2>&1 < /dev/null &
jobs -p %1

for i in `seq 5`; do
    if route add -host 192.168.19.$(($1+1)) dev tap$1 2>> $LOGFILES-$1; then
	exit 0
    fi
    echo route add failed >> $LOGFILES-$1
    sleep 1
done
exit 1

