#! /bin/sh

. ./SETTINGS

# Export this for ifup
IPADDR=192.168.12.$(($1+1))
export IPADDR

# Redirect everything so this doesn't hold pipe open.
$KVM -m 512								\
	-net nic,model=virtio -net tap,ifname=tap$1,script=kvm/ifup	\
	-nographic -hda scratchfile					\
	-kernel $KERNEL							\
	-initrd initrd.gz						\
	-append "console=ttyS0 rdinit=/virtclient $1 `echo $2 | tr . /` $3 /dev/hda 3 0 eth0 192/168/19/$(($1+1))" \
	> $LOGFILES-$1 2>&1 < /dev/null &
jobs -p %1

for i in `seq 5`; do
    if /sbin/route add -host 192.168.19.$(($1+1)) dev tap$1 2>/dev/null; then
	echo 1 > /proc/sys/net/ipv4/conf/tap$1/proxy_arp 
	exit 0
    fi
    sleep 1
done
exit 1
