#! /bin/sh

set -e

. kvm/SETTINGS

if grep -q AuthenticAMD /proc/cpuinfo; then
    modules="kvm-amd"
else
    modules="kvm-intel"
fi

[ -c /dev/kvm ] || modprobe $m

# We need to enable packet forwarding for inter-guest tests
echo 1 > /proc/sys/net/ipv4/ip_forward
