#! /bin/sh

set -e

. ./SETTINGS

if grep -q AuthenticAMD /proc/cpuinfo; then
    module="kvm-amd"
else
    module="kvm-intel"
fi

[ -c /dev/kvm ] || modprobe $module

# We need to enable packet forwarding for inter-guest tests
echo 1 > /proc/sys/net/ipv4/ip_forward
